In [4]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

import os
import cv2
from PIL import Image

### 데이터 불러오기

In [8]:
data = []
label = []
label_name = ["AC", "FL", "HC", "HUM"]

# 이미지 사이즈 조정하기
img_size = (224, 224)

for i in label_name:  # label_name 값을 i에 저장하고, 총 4번 돌아감.
    forder = f"C:/Users/JungHyeona/Desktop/KNN/{i}"
    
    for j in os.listdir(forder):  # forder 내에 있는 데이터를 j에 저장.
        if j.endswith('.png'):    # 파일 내에서 png데이터만을 가져옴.
            file = os.path.join(forder, j)
            
            img = cv2.imread(file, cv2.IMREAD_UNCHANGED)   # 이미지 데이터이기 때문에 cv2를 사용해 불러온다.
            img_resize = cv2.resize(img, img_size)         # 이미지 크기 조정
            fla = img_resize.flatten()   # 다차원 배열 공간을 1차원으로 평탄화해준다.
            
            data.append(fla)
            # label에 폴더 이름을 넣고 돌렸을 때, data와 label의 데이터 수가 달랐음.
            #   -> label = [A,~ M]으로 선언해서 데이터마다 label이 붙지 않아 오류가 발생했었음.
            label.append(i)

### 데이터 분리하기

1. train / test로 분리
2. train -> train / validation으로 분리

=> train[train/val] / test 와 같은 형식

https://wikidocs.net/33274<br>
https://wikidocs.net/43729

In [9]:
len(data)

1216

In [15]:
tr_num = int(len(data) * 0.7)
te_num = int(len(data) - tr_num)

In [16]:
print("tr_num : ", tr_num)
print("te_num : ", te_num)

tr_num :  851
te_num :  365


### 1. data를 train과 test로 분리

In [17]:
# train
X_train = data[:tr_num]    # data
y_train = label[:te_num]   # label

# test
X_test = data[tr_num:]     # data
y_test = label[te_num:]    # label

In [20]:
X_train[:10]

[array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)]

### 2. train 데이터를 train과 validation으로 분리

- train_data를 세개로 분리할 것이기 때문에 이중 배열을 사용해야함 -> [[1], [2], [3]]
  -> 이렇게 해주어야 val이 1~3까지 하나씩 골라가면서 검증을 해줄 수 있음. <br><br>
  
순서
1. X_train을 3개로 분리하기
2. 분리한 배열을 하나의 배열로 묶어주기
3. for문을 사용해 val이 하나씩 지정하는지 확인해보기(print사용해서 확인만 일단!)
<br>
### 이 작업을 마친 후에 훈련할 수 있도록 고치기

In [26]:
se = int(len(X_train) / 3)  #851 / 3 = 283(소수점 제거)
# train
for seper in range(3):
    a = int(len(X_train)) / seper
    print(a)

ZeroDivisionError: division by zero

In [35]:
se = int(len(X_train) / 3)  #851 / 3 = 283(소수점 제거)
a = X_train[:se]
b = X_train[se:se+se]
c = X_train[se+se:]

In [40]:

for(int i=0; i<3; i++):
    

285